#!/bin/sh
#
# Start the gamepad gadget....
#

case "$1" in
  start)
	printf "Starting gamepad gadget: "
	gadget_gamepad.sh
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping gamepad gadget: "
	killall gadget_gamepad.sh
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
